language: php

php:
  - 7.3
  - 8.0

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - sudo mysql -e 'create database testing_db;'
  - composer self-update --2
  - composer update
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit

notifications:
  email: false
